config/routes.rb
Rails.application.routes.draw do
  get 'messages/new'

  get 'messages/create'

  get 'messages/index'

  get 'messages/show'

  get 'messages/sent'

  get 'sessions/new'

  get 'users/new'

  resources :messages

  resources :users do
    collection do
      get :add_friend
      get :remove_friend
    end

    member do
    get :block
    get :unblock
    end

  end

  resources :sessions, only: [:new, :create]
  

  get 'home/index'
  delete 'logout' => 'sessions#destroy'

  root 'home#index'

end

app/models/block.rb
class Block < ActiveRecord::Base
    belongs_to :user
    belongs_to :blocked_user, class_name: 'User', foreign_key: 'blocked_id'
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'

  mount_uploader :photo, PhotoUploader
  


  def read?
    !!read_at
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password 

  validates :email, uniqueness: true
  validates :email, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ }
  validates :name, :email, :password, presence: true

  has_many :sent_messages, foreign_key: 'sender_id', class_name: 'Message'
  has_many :received_messages, class_name: 'Message', foreign_key: 'recipient_id'

  has_many :friendships
  has_many :friends, through: :friendships

  has_many :blocks
  has_many :blocked_users, through: :blocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
      @current_user ||= User.find_by_id session[:user_id]
  end 


  def skip_if_logged_in
    if current_user
      redirect_to messages_path
    end
  end

  def require_login
    if current_user.nil?
      redirect_to login_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :skip_if_logged_in
  
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_login

  
  def new
    @message = current_user.sent_messages.new
  end

  
  # POST /messages
  def create
    @message = Message.new(message_params)

    if @message.save
      redirect_to messages_sent_path, notice: 'Message was successfully created.'
    else
      render :new
    end
  end

  def index
    @messages = current_user.received_messages.order(created_at: :desc)

    if (ids = current_user.blocked_user_ids).any?
      @messages = @messages.where("sender_id NOT IN (?)", ids)
    end
  end

  
  # GET /messages/1
  def show
    @message = current_user.received_messages.find(params[:id])
    if @message.read_at
      redirect_to messages_path, notice: 'Message has been read before.'
    else
      @message.update_attribute(:read_at, Time.now)
    end
  end


  
  # GET /messages/sent
  def sent
    @messages = current_user.sent_messages.order(created_at: :desc)
  end


  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:sender_id, :recipient_id, :title, :body, :photo, :read_at)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Logged out."
    redirect_to root_path
  end

  def create 
    if @user = User.find_by(email: params[:email]) and @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to messages_index_path, flash: {success: "Logged in"}
    else
      flash.now[:error] = "Invalid username or password"
      render 'new'
    end
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:add_friend]

  def new
      @user = User.new
  end 

  
  def index
    @users = User.all
    @friends = current_user.friends
    @blocked_users = current_user.blocked_users 
  end

  def add_friend
    Friendship.create(user_id: current_user.id, friend_id: params[:friend_id])
    redirect_to users_path
  end

  def remove_friend
      friend = User.find(params[:friend_id])
      current_user.friends.delete(friend)
      redirect_to users_path
  end 

  def block
      Block.create(user_id: current_user.id, blocked_id: params[:id])
      redirect_to users_path
  end 

  def unblock
      user = User.find(params[:id])
      current_user.blocked_users.delete(user)
      redirect_to users_path
  end 

  def create
      @user = User.create user_params
      if @user.persisted?
        session[:user_id] = @user.id
        flash[:success] = "Registered successfully."
        redirect_to root_path
      else
        flash.now[:error] = "Error: #{@user.errors.full_messages.to_sentence}"
        render 'new'
      end
  end

  private
  def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def flash_class_name(key)
    case key.to_s
    when 'success'
      "alert-success"
    when 'error'
      "alert-danger"
    else
      "alert-warning"
    end
  end
end

app/views/home/index.html.erb
<h3>The CoderSnap Site for Users</h3>
  <p>CoderSnap is a Ruby on Rails blog application that allows users to send messages to each other that can only be read once.</p>

<h4>List of Users</h4>

<table class="table">
  <thead class="thead thead-default">
    <tr>
      <th>Name</th>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% User.all.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoderSnap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    <div class="alert alert-info">
      Welcome, <%= current_user.name %>
      
      <nav class="nav nav-inline">
        <%= link_to "Log out", logout_path, method: 'delete', class: 'nav-link' %>
        <a class="nav-link active" href="<%= messages_index_path %>">Incomming messages</a>
        <a class="nav-link" href="<%= messages_sent_path %>">Sent messages</a>
        <a class="nav-link" href="<%= new_message_path %>">New message</a>
        <a class="nav-link" href="<%= users_path %>">Add friends</a>
      </nav>
    </div>
    
  <% else %>
    <div class="alert alert-info">
      <nav class="nav nav-inline">
        <%= link_to "Log in", new_session_path, class: 'nav-link' %>
        <%= link_to "Sign Up", new_user_path, class: 'nav-link' %>
      </nav>
    </div>
  <% end %>

  <% if flash.any? %>
    <% flash.each do |key, value| %>
      <div class="alert <%= flash_class_name(key) %> ">
        <%= value %>
      </div>
    <% end %>
  <% end %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="form-group">
    <%= f.label :recipient_id, 'Recipient' %><br>
    <%= f.collection_select :recipient_id, current_user.friends, :id, :name, {}, {class: 'form-control'} %>
  </fieldset>
  <fieldset class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </fieldset>
  <fieldset class="form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: 'form-control' %>
  </fieldset>
  <fieldset class="form-group">
    <%= f.label :photo %><br>
    <%= f.file_field :photo, class: 'form-control' %>
  </fieldset>
  <fieldset class="form-group">
    <%= f.hidden_field :sender_id %>
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </fieldset>
<% end %>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Your received messages</h1>

<table class="table table-bordered table-striped">
  <thead class="thead thead-default">
    <tr>
      <th>Message from</th>
      <th>Sent at</th>
      <th>Read at</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr <%= "class=unread" if message.read_at.nil? %>>
        <td><%= message.sender.name %></td>
        <td><%= message.created_at %></td>
        <td><%= message.read_at %></td>
        <td><%= link_to('Read', message) if message.read_at.nil? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/sent.html.erb
<p id="notice"><%= notice %></p>

<h1>Your sent messages</h1>


<table class="table table-bordered table-striped">
  <thead class="thead thead-default">
    <tr>
      <th>Recipient</th>
      <th>Sent at</th>
      <th>Read at</th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.recipient.name %></td>
        <td><%= message.created_at %></td>
        <td><%= message.read_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sender:</strong>
  <%= @message.sender.name %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= @message.recipient.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @message.title %>
</p>
<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag(@message.photo.url) if @message.photo.url.present? %>
</p>

<p>
  <strong>Read at:</strong>
  <%= @message.read_at %>
</p>

<%= link_to 'Back', messages_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing of Users</h1>

<table class="table table-bordered table-striped">
  <thead class="thead thead-default">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Friendship</th>
      <th>Block</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
          <% if user == current_user %>
            Yourself
          <% elsif @friends.include?(user) %>
            Your friend (<%= link_to "Remove friendship", remove_friend_users_path(friend_id: user.id) %>)
          <% elsif @blocked_users.include?(user) %>
            Can't add friend
          <% else %>
            <%= link_to "Add as a friend", add_friend_users_path(friend_id: user.id) %> 
          <% end %>
        </td>
        <td>
          <% if user == current_user %>
            Can't block 
          <% elsif @friends.include?(user) %>
            Can't block 
          <% elsif @blocked_users.include?(user) %>
            <%= link_to "Unblock user", unblock_user_path(user) %>
          <% else %>
            <%= link_to "Block user", block_user_path(user) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Register</h1>


<%= simple_form_for @user do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.submit %>
<% end %>